name: Java CI con Maven

on:
  push:
    branches: [ "main", "master" ] # Se ejecuta cuando subes código a estas ramas
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga el código del repositorio al servidor de GitHub
    - name: Checkout de código
      uses: actions/checkout@v4

    # 2. Configura Java 21 (debe coincidir con tu pom.xml)
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin' # Distribución recomendada y estable
        cache: maven            # Esto acelera las descargas de librerías en el futuro

    # 3. Ejecuta la compilación y los tests
    - name: Build with Maven
      run: mvn -B clean install
